development:
  adapter: postgresql
  encoding: unicode
  database: pong-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pong-test
  pool: 5
  port: 5432
  host: localhost

  production:
    adapter: postgresql
    encoding: unicode
    database: pong-development